#cloud-config
groups:
  - ubuntu: [root,sys]
  - terraform

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB

packages:
  - apache2

runcmd:
  - sudo apt-get update && apt-get -y dist-upgrade
  - sudo echo "Hello World from `hostname`" >/var/www/html/index.html

